on: push
name: Clippy & Tests

jobs:
  clippy_check:
    name: Clippy check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Clippy
        run: cargo clippy --all-targets --all-features
        # Make sure CI fails on all warnings, including Clippy lints
        env:
          RUSTFLAGS: "-Dwarnings"

  run_tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run tests
        run: cargo test
        timeout-minutes: 5